alias: Meshtastic Node - retain topics
description: ""
trigger:
  - platform: mqtt
    topic: msh/pa8f/2500-2599/2/json/LongFast/!433c9f4c
    value_template: |
      {% if value_json.type == "position" %}on{% endif %}
    payload: "on"
    id: position
    enabled: true
  - platform: mqtt
    topic: msh/pa8f/2500-2599/2/json/LongFast/!433c9f4c
    value_template: |
      {% if value_json.type == "telemetry" and 
            value_json.payload.air_util_tx is defined %}on{% endif %}
    payload: "on"
    id: device_metrics
  - platform: mqtt
    topic: msh/pa8f/2500-2599/2/json/LongFast/!433c9f4c
    value_template: |
      {% if value_json.type == "telemetry" and 
            value_json.payload.barometric_pressure is defined %}on{% endif %}
    payload: "on"
    id: environment_metrics
  - platform: mqtt
    topic: msh/pa8f/2500-2599/2/json/LongFast/!433c9f4c
    value_template: |
      {% if value_json.type == "telemetry" and 
            value_json.payload.current_ch1 is defined %}on{% endif %}
    payload: "on"
    id: power_metrics
  - platform: mqtt
    topic: msh/pa8f/2500-2599/2/json/LongFast/!433c9f4c
    value_template: |
      {% if value_json.type == "nodeinfo" %}on{% endif %}
    payload: "on"
    id: nodeinfo
  - platform: mqtt
    topic: msh/pa8f/2500-2599/2/json/LongFast/!433c9f4c
    value_template: |
      {% if value_json.type == "text" %}on{% endif %}
    payload: "on"
    id: text
    enabled: true
condition: []
action:
  - variables:
      nodeid: "{{ (trigger.payload | from_json).from }}"
  - action: mqtt.publish
    metadata: {}
    data:
      topic: meshtastic/{{ nodeid }}/{{trigger.id}}
      payload: "{{ trigger.payload }}"
      qos: 0
      retain: true
    enabled: true
  - action: mqtt.publish
    metadata: {}
    data:
      topic: meshtastic/{{ nodeid }}/all
      payload: "{{ trigger.payload }}"
      qos: 0
      retain: true
    enabled: true
mode: single
